controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


projects:
    path:       /
    controller: App\Controller\ProjectsController::userProjects
